### ISSUE TITLE
Go mod 1.22 breaks autocomplete 

### ISSUE THREAD

**Issue by mattbrandman** [templ-go/templ-jetbrains#16]
When updating gomod to Go 1.22 from Go 1.22rc1 it seems that all autocompletion breaks.

**Comment by danielmichaels** [comment]
I seem to have lost auto complete as well.

Goland 2023.3.4
Templ Version: 0.2.543
Templ Goland Plugin version: 0.0.12

I reverted to my last known working state, Templ Plugin v0.0.9 and autocomplete returned.

Inspecting the jetbrains debug logs returned nothing. Apologies that I don't have much more info to share.

**Comment by vputtaparthi** [comment]
Any update on this?

**Comment by vputtaparthi** [comment]
> I seem to have lost auto complete as well.
> 
> Goland 2023.3.4 Templ Version: 0.2.543 Templ Goland Plugin version: 0.0.12
> 
> I reverted to my last known working state, Templ Plugin v0.0.9 and autocomplete returned.
> 
> Inspecting the jetbrains debug logs returned nothing. Apologies that I don't have much more info to share.
> 
> I don't know much about Kotlin/JB plugin development but both Templ and Goland are invaluable to me. If you can provide some documentation to assist, or provide better debug output please let me know.

What is the best way to rollback to an old version on goland?

**Comment by vputtaparthi** [comment]
Any update on this? I downloaded v0.0.9 and it still does not work on mac goland

**Comment by nmcbride** [comment]
I just tried using it on my first project and it doesn't seem to be working here either.

**Comment by nmcbride** [comment]
When I run goland from the command line I see the following error:
```
2024-02-22 12:13:52,874 [  31725]   WARN - #o.j.p.t.l.s.SyntaxNodeDescriptor - Can't find repository 52
2024-02-22 12:16:58,030 [ 216881]   WARN - #c.i.e.p.BaseOSProcessHandler - Process hasn't generated any output for a long time.
If it's a long-running mostly idle daemon process, consider overriding OSProcessHandler#readerOptions with 'BaseOutputReader.Options.forMostlySilentProcess()' to reduce CPU usage.
Command line: /var/home/<user>/go/bin/templ lsp
java.lang.Throwable: Process creation:
	at com.intellij.execution.process.BaseOSProcessHandler.<init>(BaseOSProcessHandler.java:32)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:44)
	at com.intellij.platform.lsp.api.LspServerDescriptor.startServerProcess(LspServerDescriptor.kt:95)
	at com.intellij.platform.lsp.impl.connector.Lsp4jServerConnectorStdio.<init>(Lsp4jServerConnectorStdio.java:19)
	at com.intellij.platform.lsp.impl.LspServerImpl.N(LspServerImpl.java:383)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
	```

**Comment by tigrang** [comment]
I had to `go install golang.org/x/tools/gopls@latest` to get it to work.

Run `templ lsp -log templ.log` and check templ.log to see if you have the same issue.

**Comment by nmcbride** [comment]
@tigrand

I did the same but that doesn't allow goland to actually use the LSP. You can see in the error there is a process execution issue executing templ. And the plugin itself doesn't have the options to configure a log output like the vscode one does to see what is actually going on.

**Comment by tigrang** [comment]
@nmcbride I found my issue looking in these directories https://www.jetbrains.com/help/go/directories-used-by-the-ide-to-store-settings-caches-plugins-and-logs.html#logs-directory

**Comment by vputtaparthi** [comment]
> I had to `go install golang.org/x/tools/gopls@latest` to get it to work.
> 
> Run `templ lsp -log templ.log` and check templ.log to see if you have the same issue.

This fixed my issue as well! thank you!

**Comment by joerdav** [comment]
Thanks @tigrang for the resolution!
